apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team-f-prod
  namespace: team-f
spec:
  releaseName: team-e-prod
  chart:
    git: https://github.com/sameeraman/todo-app-helm.git
    path: todo-app-helm
    ref: master
  values:
    image:
      repository: prydonius/todo
      pullPolicy: IfNotPresent
      tag: "1.0.0"
    replicaCount: 3
    service:
      type: NodePort
      port: 80
